---
title: "The evolution of social effects in breeding time"
author: "Andres Quiñones"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
documentclass: extarticle
bibliography: time2breed.bib
fontsize: 12pt
linespread: 2
header-includes:
   - \linespread{2}
   - \usepackage{lineno}
   - \linenumbers
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Justification

In natural populations, reproductive success depends on the availability of the 
resources necessary for reproduction. Resources typically vary in space and time.
Predicting the abundance of resources can be extremely important for organisms, particularly 
for those that need time to prepare for a reproductive event. The spatial and 
temporal variation in resource availability can be, to some extent, 
predicted through environemental cues. For example, resource availability in the 
temperate zones varies temporally with the seasons. Thus, 
resource availability can be predicted by environmental cues that vary periodically 
along the year, for instance photoperiod. Thus, in order to match, the physiological 
processes required for reproduction with high abundance of resources, it makes sense for 
organisms to use environmental correlates of resource abundance in their 
reproductive desicions. 

This correlation between resource abundance and environmental
cues is, however, not perfect. This means that, if individuals use environmental cues 
to decide when to reproduce, on certain occassions the cues will provide erroneous information, 
leading to a mismatch between reproduction and resource abundance. Furthermore, one expects 
a certain level of error in the perception of environmental cues by individuals. 
In order to reduce the mismatch, particularly generated by the perception error, 
individuals could include the reproductive desicion of their peers into their 
decision making process. This desicion making strategy could, however, come with 
some trade offs. One potencial cost is, if all individuals respond to the social influence,
breeding time might end up being overly concentrated in time. The excessive cooprdination in breeding,
due to density dependence, might reduce the reproductive success. 
Thus, depending on the strength of the intra-specific competition, it might be 
better for individuals to respond less to their peers. 

The question of breeding time in a sexual population has some interesting complications.
The balance between information aquisition and intra-specific competition described
above applies to females only. For whom resources for offspring provisioning is of 
outmost importance. For males however, it's more important to find mates. Thus, 
environmental information is useful for males only as a proxy of female availability. 
Perhaps, the social influence is a more direct cue of the availability of reproductive 
females. This does not mean that males do not experience density dependence effects. 
If a male happens to be reproductively active when abunduce of females is low, but 
abundance of reproductively active males even lower, such male might enjoy a high 
reproductice success. Which opens up the question, what is the best strategy for a 
male to decide when to become reproductively active?


In order to assess the effect that natural selection could have
on the evolution of the desicion making mechanisms, we develop an evolutionary model. 
In the model, we let individuals evolve the sensitivity to include in their decision 
making process of when to breed the reproductive status of their conspecifics. 
We start with an asexual population. Individuals can use an environmental cue to decide when, 
during the year, to breed. This environmental cue is partly correlated with the abundance of 
resources along the season. Specifically, we let the mean abundance of resources 
along the year be random variable determined by the Von Mises distribution [@mardia_directional_1999], 
which is a circular analogue of the normal distribution. By using the Von Mises distribution, 
we assume that resources have one peak of abundance during the year. Also, by tuning 
parameters $\kappa$ and $\mu$ in the distribution, we can control how high and spread 
is the peak of resources, respectively. The actual abundance of resource 
These resources are necessary to raise the offspring, 
and thus reproductive success (or offspring survival) depends on the *per capita* 
availability of resources. The perception of the environmental cue by each individual 
is prone to errors. So, the mismatch between the perceived cue, and the resource 
variation not predicted by the environmental cue, could potentially trigger individual
breeding at the wrong time. Hence, individuals could improve their decision making by 
taking into account the breeding status of their peers, which could potentially 
improve the accuracy of their decision by pulling together individual and social information. 

	 


We aim to answer the above questions using a individual based model. In such model,
individuals have genotypes that define their response to an environmental cue, as well 
as the reproductive status of other individuals. The decision of whether to breed at a particular  time is given the log odds equation from a logistic regression

\begin{equation}
	log\frac{p}{1-p}=\beta_0+e \beta_e+s \beta_s+
\end{equation}
